[tool.ruff]
line-length = 100
target-version = "py311"
lint.select = ["E", "F", "I"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q"
testpaths = [
  "tests",
]

[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = true
disallow_incomplete_defs = false
ignore_missing_imports = true
check_untyped_defs = false
warn_unused_ignores = false

